### ISSUE TITLE
Change config mechanisms

### ISSUE THREAD

**Issue by nbarray** [winamax/aquedux#1]
It would be great to have a single file `config.js` foreach projects that gather the initialization of every `process.env` variables.

Here is an exhaustive list foreach projects:

* aquedux-server:
    * [ ] AQUEDUX_REDIS_PORT
	* [ ] DB_PORT_6379_TCP_PORT
    * [ ] AQUEDUX_REDIS_HOST
    * [ ] DB_PORT_6379_TCP_ADDR
    * [ ] AQUEDUX_SECRET
    * [ ] AQUEDUX_BUNYAN_LEVEL

* aquedux-client:
   * [ ] REACT_APP_AQUEDUX_BUNYAN_LEVEL

**Comment by chabou** [comment]
Env var should be replaced by explicit options on Aquedux creation/instanciation.

Other configuration steps like `setReduceStateToQueueSnapshot` should be done similary.
