### ISSUE TITLE
Isolate internal state

### ISSUE THREAD

**Issue by yahwastaken** [winamax/aquedux#23]
The idea is because we are constantly overriding parts of the Redux api (createStore and combineReducer for now) it should be easier to import directly the Redux api from aquedux.

```js
import {
  createStore,              // Overriden for our internal mechanisms
  combineReducer,           // Overriden for our internal mechanisms
  applyMiddleware,          // Just exporting the Redux function
  bindActionCreator         // Just exporting the Redux function
} from 'aquedux-client'     // The same goes for aquedux-server
```

This would greatly simplify the use of aquedux: "just replace the Redux import" should be our short goal.

Also, the createAquedux{Client,Server} should check if the mandatory overriden functions are used adn throw a warning in development pointing out the mistake.

**Comment by chabou** [comment]
WIP here: https://github.com/chabou/aquedux/tree/move_internals

**Comment by yahwastaken** [comment]
After much discussion, the aquedux API takes another turn. See #30
